name: 'Publish Docker Container to GitHub Packages'

on:
  workflow_dispatch:
    inputs:
      image-name:
        description: 'Name of the Docker image to build'
        required: true
        default: 'kotlin-docker'
        type: string

      image-version:
        description: 'Version of the Docker image to build'
        required: true
        default: 'latest'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‚ Checkout
        uses: JavierSegoviaCordoba/actions/git/checkout@main

      - name: ğŸ˜ Setup Gradle
        uses: JavierSegoviaCordoba/actions/gradle/setup@main

      - name: ğŸ› ï¸ Build
        run: |
          ./gradlew build
          ./gradlew installDist

      - name: ğŸ™ Publish Docker Container to GitHub Packages
        uses: JavierSegoviaCordoba/actions/docker/publish-github-packages@main
        with:
          github-token: ${{ secrets.PAT }}
          image-name: ${{ github.event.inputs.image-name }}
          image-version: ${{ github.event.inputs.image-version }}
